apiVersion: v1
kind: Service
metadata:
  name: foodapp-service
  labels:
    app: foodapp-service-label
spec:
  type: NodePort
  selector:
    app: foodapp-pod
  ports:
    - protocol: TCP
      port: 3000                #service should listen on port 8081
      targetPort: 3000       #service will route traffic to this port to the pod that matches the selector
      nodePort: 30200 